yiisoft/view

src/widgets/ActiveFormClientScript.php, src/widgets/FragmentCache.php, src/widgets/Widget.php
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
fix class definition needed for debug module tests to pass
=> fix class definition for debug module tests

tests/unit/widgets/ActiveFormTest.php, tests/unit/widgets/BlockTest.php, tests/unit/widgets/BreadcrumbsTest.php, tests/unit/widgets/ContentDecoratorTest.php, tests/unit/widgets/FragmentCacheTest.php, tests/unit/widgets/LinkPagerTest.php
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
Added some test fixes. I do not know how to fix InitEvents and FragmentCache failures, @hiqsol any ideas ?
=> Fixed some tests fatal errors

src/Asset/AssetConverter.php
The method signature is in accordance with the interface.
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | no
=> fix_convert

config/common.php
\yii\di\Reference -> Yiisoft\Factory\Definitions\Reference
\yii\view\View -> Yiisoft\View\View
\yii\view\Theme -> Yiisoft\View\Theme
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | no
=> common_config_fix

composer.json, config/common.php
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  |
=> Update dependencies and adjust to yiisoft/di changes

src/View/WebView.php, tests/Asset/AssetBundleTest.php, tests/View/WebViewTest.php
| Tests pass?   | ❌
| Fixed issues  | #61
=> full name for constants #61

src/DynamicContentAwareTrait.php
=> Fix typehint propierty.

config/tests.php, src/View.php, src/WebView.php, tests/Mocks/WebViewPlaceholderMock.php, tests/TestCase.php, tests/ViewTest.php, tests/WebViewTest.php
=> View/WebView with placeholder salt #62

tests/Mocks/WebViewPlaceholderMock.php
=> add feature declare all packets

.github/workflows/mutation.yml
| Fixed issues  | Should replace #85 
Workaround as per https://github.com/infection/infection/issues/1283
=> Fix Infection workflow

.github/workflows/mutation.yml
- Require at least 10% MSI and covered MSI.
| Fixed issues  | n/a
=> Update mutation testing workflow to include limits

.github/workflows/build.yml, .github/workflows/static.yml, composer.json, psalm.xml, src/PhpTemplateRenderer.php, src/View.php, src/WebView.php, tests/TestCase.php, tests/ThemeTest.php, tests/ViewTest.php, tests/WebViewTest.php
=> Fixed all tests.

src/View.php
| Fixed issues  | 
I propose to fix it by analogy with ArrayHelper.
https://github.com/yiisoft/arrays/blob/3fad714d9f8325fe9eb1bfac48d3fee70e68b860/src/ArrayHelper.php#L551
=> View->unsetBlock => View->removeBlock

composer.json
=> Remove packages unsed.

config/common.php
=> Fix config theme pathMap.

src/WebView.php
=> Fix break bc html.

src/WebView.php, tests/WebViewTest.php
Adopt to https://github.com/yiisoft/html/pull/52
=> Adopt to yiisoft/html PR #52

composer.json, config/common.php
=> Add View class config

src/View.php, tests/TestCase.php, tests/WebViewTest.php
=> In View move Theme from constructor to method withTheme

composer.json, tests/TestCase.php
=> Replace dev-dependency yiisoft/di to yiisoft/test-support.

config/common.php, config/web.php, src/View.php
Merge after https://github.com/yiisoft/factory/pull/78
=> Adopt configs to new factory syntax

src/Theme.php, src/View.php, src/WebView.php, tests/TestCase.php, tests/ViewTest.php
=> Fix render relative path in view

src/Event/ViewEvent.php, src/View.php, tests/WebViewTest.php, tests/public/view/only-content.php
=> Fixed error on WebView::renderAjax with path relative to basePath

composer.json, src/WebView.php, tests/WebViewTest.php
=> Add WebView::registerScriptTag

config/common.php, config/web.php
Merge after yiisoft/factory#86
=> Disallow definition objects in configs, except ReferenceInterface

psalm.xml, src/BaseView.php, src/PhpTemplateRenderer.php, src/View.php, src/WebView.php
=> Psalm level 2

src/WebView.php, tests/WebViewTest.php
Adopt PRs:
https://github.com/yiisoft/app/pull/164
https://github.com/yiisoft/yii-demo/pull/302
https://github.com/yiisoft/yii-swagger/pull/29
=> Rename WebView methods setJsFiles, setJsStrings, setJsVars, setCssFiles, setCssStrings to add*

src/BaseView.php, tests/ViewTest.php
=> Refactoring default parameters feature to BaseView

config/common.php, config/params.php, config/web.php
=> Fix configuration due to refactoring default parameters

config/common.php, config/web.php, src/BaseView.php
=> Add setCommonParameters() method to BaseView

config/common.php, config/web.php, src/BaseView.php, src/WebView.php
=> Add reset to configurations, add BaseView::clear() method

composer.json, src/BaseView.php, tests/TestSupport/TestHelper.php
=> Remove logger usage

src/WebView.php, tests/CachedContentTest.php, tests/ViewTest.php, tests/WebViewTest.php
=> Add more tests

src/Theme.php
=> Minor refactoring `Theme` class

src/BaseView.php
=> Make beforeRender() and afterRender() methods protected

.gitattributes, composer.json
=> Improve .gitattributes and update dev dependencies

.github/workflows/build.yml, .github/workflows/mutation.yml, .github/workflows/static.yml, composer.json, docs/basic-functionality.md, docs/use-in-web-environment.md, src/BaseView.php, src/Theme.php
=> Cleanup and minor improvements

CHANGELOG.md, src/Event/WebView/BeforeRender.php, src/Event/WebView/BodyBegin.php, src/Event/WebView/BodyEnd.php, src/Event/WebView/PageBegin.php, src/Event/WebView/PageEnd.php, src/Exception/ViewNotFoundException.php
=> Add final to classes

CHANGELOG.md, src/BaseView.php, tests/ViewTest.php
=> Add default value to `BaseView::getCommonParameter()`

docs/basic-functionality.md, src/PhpTemplateRenderer.php, src/View.php, src/WebView.php
=> Fix static analysis tests and description common parameters

CHANGELOG.md, config/common.php, config/web.php
=> Adopt to `yiisoft/definitions`

CHANGELOG.md, src/BaseView.php, tests/ViewTest.php
=> Add immutable methods `View::withAddedCommonParameters()` and `WebView::withAddedCommonParameters()`

CHANGELOG.md, config/web.php
=> Fix incorrect method in `web` configuration

docs/use-in-web-environment.md
Waiting: https://github.com/yiisoft/assets/pull/88
=> Fix docs due register to yiisoft/assets package changes

CHANGELOG.md, composer.json, docs/basic-functionality.md, src/State/StateTrait.php, src/Theme.php, src/ViewInterface.php, src/ViewTrait.php, tests/ViewTest.php, tests/WebViewTest.php
| Fixed issues  | #196 
Tests in demo and app pass.
=> Move theme and language to view state

README.md, src/Cache/CachedContent.php, src/Cache/DynamicContent.php, src/PhpTemplateRenderer.php, src/TemplateRendererInterface.php, src/Theme.php, src/View.php, src/ViewContextInterface.php, src/ViewTrait.php, src/WebView.php
=> Fix readme and minor improve phpdoc

docs/basic-functionality.md, docs/use-in-web-environment.md, src/Cache/CachedContent.php, tests/ViewTest.php, tests/public/view/change-context.php
| Readability fix  | according to https://github.com/yiisoft/docs/issues/155, chain calls must be put on separate lines.
=> Separate chain calls

CHANGELOG.md, src/ViewInterface.php, src/ViewTrait.php, tests/ViewTest.php
=> Add `ViewInterface::withBasePath()`

CHANGELOG.md, composer.json
=> PR for issue-208

CHANGELOG.md, src/ViewTrait.php, tests/ViewTest.php
=> Support multiple fallback extensions

CHANGELOG.md, composer.json, src/State/StateTrait.php, src/State/ThemeState.php, src/View.php, src/ViewInterface.php, src/ViewTrait.php, src/WebView.php, tests/ViewTest.php
=> Add immutable withTheme method

composer.json
| Fixed issues  | resolve https://github.com/yiisoft/view/issues/252
=> upd irc link

docs/use-in-web-environment.md
| Fixed issues  | resolve https://github.com/yiisoft/view/issues/254
=> update docs folder links

src/State/WebViewState.php, src/WebView.php
| Fixed issues  | resolve https://github.com/yiisoft/view/issues/256
=> update src folder links

.github/workflows/static.yml, CHANGELOG.md, composer.json, psalm83.xml, rector.php, src/ViewInterface.php
=> Add types to `ViewInterface::setParameter()` and `ViewInterface::addToParameter()` parameters

.github/workflows/bc.yml, .github/workflows/build.yml, .github/workflows/composer-require-checker.yml, .github/workflows/mutation.yml
=> Improve CI actions

src/State/LocaleState.php, tests/WebViewTest.php
=> Test coverage 100%

README.md, docs/guide/pt-BR/README.md
=> Rename `yii-view` to `yii-view-renderer`

CHANGELOG.md, UPGRADE.md, docs/guide/en/basic-functionality.md, docs/guide/en/use-in-web-environment.md, src/Event/View/AfterRender.php, src/Event/View/BeforeRender.php, src/Event/WebView/AfterRender.php, src/Event/WebView/BeforeRender.php, src/ViewInterface.php, src/ViewTrait.php, src/WebView.php, tests/ViewTest.php, tests/WebViewTest.php
=> Change logic of template file searching

CHANGELOG.md, UPGRADE.md, config/di-web.php, config/di.php, config/params.php, src/ViewInterface.php, src/ViewTrait.php, tests/ConfigTest.php, tests/ViewTest.php
=> Remove deprecated methods + Rename config parameter `defaultExtension`

README.md
=> Fix PHP version in readme

CHANGELOG.md, composer-require-checker.json, composer.json
=> Make `psr/event-dispatcher` dependency optional

CHANGELOG.md, README.md, UPGRADE.md, composer.json, src/View.php, src/ViewInterface.php, src/WebView.php, tests/ViewTest.php, tests/WebViewTest.php
This is need to fix https://github.com/yiisoft/yii-view-renderer/issues/137
=> Add `ViewInterface::deepClone()` + Bump dev packages
