yiisoft/view

src/Asset/AssetManager.php, tests/View/WebViewTest.php
Fixed: Argument 1 passed to Yiisoft\Aliases\Aliases::isAlias() must be of the type string, null given, called in src/Aliases.php on line 132.
Fixed PHP_EOL in testcase
=> AssetManager fix

src/Widget/Block.php, src/Widget/Breadcrumbs.php, src/Widget/ContentDecorator.php, src/Widget/Menu.php, src/Widget/Widget.php, tests/Widget/Stubs/TestWidget.php
| Tests pass?   | ❌
`Widget::begin()`, `Widget::end()`, `Widget::widget()` at now has typehint for child class
=> Fix typehint

src/WebView.php
I was not sure an empty string or `null` would be the preferred solution, but in case `null` is preferred this can easily be adjusted.
=> Prevent error if title is not set

composer.json, config/params.php
PR replace value of `$params['yiisoft/view']['basePath']` from `@views` to empty string.
For example, I can use in console app `yiisoft/yii-db-migration` which used `yiisoft/view`. `@views` in my app not setted and throws error.
In [app template](https://github.com/yiisoft/app/blob/master/config/params.php#L57) and [demo app](https://github.com/yiisoft/yii-demo/blob/master/config/params.php#L51)  `$params['yiisoft/view']['basePath']` already is `@views`.
=> Fix config + Update dev dependencies

src/WebView.php
=> The type attribute is unnecessary for JavaScript resources.

src/WebView.php
CSRF not for this package.
In `yii-view` has csrf injection.
=> Remove WebView::registerCsrfMetaTags()

src/View.php, src/WebView.php
| Is bugfix?    | ✔️/❌ (might be)
| Breaks BC?    | ✔️/❌ (potential)
| Fixed issues  | n/a
- add couple missing param `string` type declarations
- remove reference from param as it is not used in body (should it propagate to `AfterRender` by design?)
p.s. `afterRender` function phpDoc is missing `@return` declaration
=> Minor fixes

src/BaseView.php, src/WebView.php, tests/WebViewTest.php
`WebView::registerMeta()` and `WebView::registerLink()` take arrays.
`WebView::registerMetaTag()` and `WebView::registerLinkTag()` take tag objects from `yiisoft/html`.
Successfully tested with demo application.
Adopt PRs:
https://github.com/yiisoft/yii-view/pull/30
https://github.com/yiisoft/demo/pull/306
=> Add methods WebView::registerMeta() and WebView::registerLink() + support position for link tags

src/PhpTemplateRenderer.php, src/Theme.php, tests/CachedContentTest.php, tests/PhpTemplateRendererTest.php, tests/ThemeTest.php, tests/WebViewTest.php, tests/public/view/error.php, tests/public/view/rawlayout.php
- Fix PhpTemplateRenderer: in some cases throw exception in view leads to an infinite loop
- Trim right slash in theme base URL
- Minor refactoring `Theme` class
- Add more tests, test coverage 100%, MSI 99%
- Remove unnecessary file in tests
=> Fix bug, minor improvements, more tests, test coverage 100%, MSI 99%

CHANGELOG.md, config/common.php, config/params.php, config/web.php, docs/basic-functionality.md, src/BaseView.php, src/PhpTemplateRenderer.php, src/TemplateRendererInterface.php, src/WebView.php, tests/ViewTest.php, tests/WebViewTest.php
Adopt PRs: https://github.com/yiisoft/app/pull/194 and https://github.com/yiisoft/demo/pull/355
Tests in `yiisoft/app-api` and `yiisoft/demo-api` is passed.
=> Remove `BaseView::withAddedCommonParameters()`, rename "commonParameters" to "parameters", add fluent interface for setters in view classes

CHANGELOG.md, composer.json, src/ViewContext.php, src/ViewTrait.php, tests/ViewContextTest.php, tests/ViewTest.php
For example, this class convient use in widgets:
```php
final class SidebarMenu extends Widget
{
public function __construct(
private View $view
) {
$this->view = $this->view->withContext(new ViewContext(__DIR__));
}
protected function run(): string
{
return $this->view->render('menu');
}
}
```
or so:
```php
final class SidebarMenu extends Widget
{
public function __construct(
private View $view
) {
$this->view = $this->view->withContextPath(__DIR__);
}
protected function run(): string
{
return $this->view->render('menu');
}
}
```
This is better, than:
```php
final class SidebarMenu extends Widget implements ViewContextInterface
{
public function __construct(
private …
```
=> Add simple view context class `ViewContext` and methods `View::withContextPath()` and `WebView::withContextPath()`

CHANGELOG.md, src/ViewTrait.php, tests/ViewTest.php
For example, this method will be useful for breadcrumbs: 
```php
// Add in view
$this->addToArrayParameter('breadcrumbs', $item1, $item2);
// Get in layout
$breadcrumbs = $this->getParameter('breadcrumbs') ?? [];
```
=> Add `ViewTrait::addToArrayParameter()` and more tests

CHANGELOG.md, src/ViewInterface.php, src/ViewTrait.php, tests/ViewTest.php
=> Make fallback extension configurable

docs/basic-functionality.md
=> Fix fallback extension section in docs

CHANGELOG.md, src/ViewInterface.php, src/ViewTrait.php, tests/ViewTest.php
It needs to get current locale when page is rendering
`<html lang="<?= Html::encode($view->getLocale()) ?>">`
Also this will allow fix issue yiisoft/app#290
=> Add `getLocale()` method

CHANGELOG.md, src/View.php, src/ViewTrait.php, src/WebView.php, tests/TestSupport/TestHelper.php
=> Make event dispatcher in `View` and `WebView` optional

CHANGELOG.md, src/View.php, src/ViewTrait.php, src/WebView.php, tests/ViewTest.php
=> Make base path in `View` and `WebView` optional

docs/guides/en/basic-functionality.md, docs/guides/en/use-in-web-environment.md, docs/guides/pt-BR/basic-functionality.md, docs/guides/pt-BR/use-in-web-environment.md
Note the following:
- created folders according to the documentation standard
- added the logo at the beginning of all files *
- several link corrections (en and pt)
- various concept corrections
- see preview in https://github.com/luizcmarin/view/tree/master/docs/guides
- ...
* done to evaluate visual impact. If accepted, I will make corrections to all my forks.
=> Translation into Brazilian Portuguese and corrections to the documeation in English.

CHANGELOG.md, UPGRADE.md, src/State/StateTrait.php, src/ViewInterface.php, src/ViewTrait.php
=> Add variadic parameter `$default` to `ViewInterface::getParameter()`

CHANGELOG.md, psalm.xml, psalm83.xml, src/State/WebViewState.php, tests/WebViewTest.php
=> Fix empty string and "0" keys usage for CSS/JS in `WebView` + Improve psalm

CHANGELOG.md, src/ViewInterface.php, src/ViewTrait.php, tests/View/ResetContext/ResetContextTest.php, tests/View/ResetContext/views-base/test.php, tests/View/ResetContext/views-context/test.php, tests/ViewTest.php
=> Allow to pass `null` to `ViewInterface` methods `withBasePath()` and `withContext()`

CHANGELOG.md, config/di-web.php, tests/ConfigTest.php
Allows you to use a directory array as the source of the view files, as described in the documentation of the Theme class
Without this, when configuring a theme with multiple paths, the following error occurs
```
'yiisoft/view' => [
'theme' => [
'pathMap' => [
'/app/views' => [
'/app/themes/christmas',
'/app/themes/basic',
],
],
...
],
],
```
now you can set up a theme as described in the Theme documentation, for multiple cascading directories, as this is the main functionality of Theme
=> Fix `di-web` for theme `pathMap` configuration with multiple paths
